name: API Test

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: phishing-api

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test